name: Codespace
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/chcekout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dpendencies
      run:
        make install
